---
# roles/compose-deploy/tasks/main.yml

- name: Vérifier si Docker Compose v2 est installé
  ansible.builtin.command:
    cmd: docker compose version
  register: compose_version
  ignore_errors: true

- name: Installer Docker Compose v2 si absent
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: compose_version.failed
  become: true

- name: Lancer la stack Docker (Compose v2)
  community.docker.docker_compose_v2:
    project_src: /home/rt/projet-sae502/docker   # chemin absolu vers docker-compose.yml
    state: present                               # crée et démarre la stack
    recreate: always                             # recrée toujours les conteneurs existants
  become: true

- name: Supprimer les conteneurs existants (orphans)
  community.docker.docker_compose_v2:
    project_src: /home/rt/projet-sae502/docker
    state: absent
    remove_orphans: true
    remove_volumes: false
    recreate: auto
