# DNS commun à tous les services
x-dns: &default-dns
  dns:
    - 172.30.0.3

services:

  infraboard-dns:
    image: internetsystemsconsortium/bind9:9.20
    container_name: infraboard-dns
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zones:/etc/bind/zones
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.3

  infraboard-web:
    image: nginx:alpine
    container_name: infraboard-web
    <<: *default-dns
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.4

  infraboard-dashboard:
    image: nginx:alpine
    container_name: infraboard-dashboard
    <<: *default-dns
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8001:80"
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.5

  infraboard-db:
    image: postgres:15
    container_name: infraboard-db
    <<: *default-dns
    environment:
      POSTGRES_DB: infraboard
      POSTGRES_USER: infraboard
      POSTGRES_PASSWORD: infraboard
    ports:
      - "5432:5432"
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.6

  infraboard-collector:
    image: python:3.11
    container_name: infraboard-collector
    <<: *default-dns
    command: sleep infinity
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.7

  infraboard-syslog:
    image: balabit/syslog-ng:latest
    container_name: infraboard-syslog
    <<: *default-dns
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.8

  infraboard-router:
    image: alpine
    container_name: infraboard-router
    <<: *default-dns
    command: sleep infinity
    networks:
      infraboard-net:
        ipv4_address: 172.30.0.9

networks:
  infraboard-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
